export const allowedPlaneProjects = [
  "Abstract Ideas",
  "Moving Framework",
  "Input Framework",
  "Camera Framework",
  "Interaction Framework",
  "Combat Framework",
  "Melee Combat",
  "Ranged Combat",
  "Horde Framework",
  "Spawn Framework",
  "Enemy Framework",
  "Enemy AI",
  "Enemy Archetypes",
  "Body Part Framework",
  "Infection Framework",
  "Morphogenesis",
  "Dissolve Framework",
  "Player Framework",
  "Health and Survival",
  "Weapons",
  "Inventory Framework",
  "Items",
  "Loot Framework",
  "Resources",
  "Crafting and Processing",
  "Progression Framework",
  "Perk Framework",
  "Evolution",
  "Synthesis",
  "Legion",
  "Level Framework",
  "Territory and Hub",
  "Missions",
  "Quest Framework",
  "Narrative",
  "Lore",
  "Characters",
  "Dialogue",
  "Factions",
  "UI and UX",
  "Debug UI and Tools",
  "Save System",
  "Data Depot Framework",
  "Audio",
  "VFX",
  "Animation",
  "Art Direction",
  "Optimization",
  "Technical Debt",
  "Bugs",
  "Build and Release",
  "Research",
  "Production"
] as const;

export type AllowedPlaneProject = (typeof allowedPlaneProjects)[number];
